const US_100B_TOP_200 = [
  ['NVDA', 'NVIDIA CORP'],
  ['GOOGL', 'Alphabet Inc.'],
  ['GOOG', 'Alphabet Inc.'],
  ['AAPL', 'Apple Inc.'],
  ['MSFT', 'MICROSOFT CORP'],
  ['AMZN', 'AMAZON COM INC'],
  ['TSM', 'TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD'],
  ['SPCX', 'SPACE EXPLORATION TECHNOLOGIES CORP'],
  ['AVGO', 'Broadcom Inc.'],
  ['TSLA', 'Tesla, Inc.'],
  ['META', 'Meta Platforms, Inc.'],
  ['MU', 'MICRON TECHNOLOGY INC'],
  ['BRK-A', 'BERKSHIRE HATHAWAY INC'],
  ['BRK-B', 'BERKSHIRE HATHAWAY INC'],
  ['LLY', 'ELI LILLY & Co'],
  ['AMD', 'ADVANCED MICRO DEVICES INC'],
  ['WMT', 'Walmart Inc.'],
  ['JPM', 'JPMORGAN CHASE & CO'],
  ['ASML', 'ASML HOLDING NV'],
  ['ASMLF', 'ASML HOLDING NV'],
  ['INTC', 'INTEL CORP'],
  ['V', 'VISA INC.'],
  ['JNJ', 'JOHNSON & JOHNSON'],
  ['AMAT', 'APPLIED MATERIALS INC /DE'],
  ['XOM', 'EXXON MOBIL CORP'],
  ['LRCX', 'LAM RESEARCH CORP'],
  ['CAT', 'CATERPILLAR INC'],
  ['CSCO', 'CISCO SYSTEMS, INC.'],
  ['MA', 'Mastercard Inc'],
  ['TSMWF', 'TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD'],
  ['ABBV', 'AbbVie Inc.'],
  ['ORCL', 'ORACLE CORP'],
  ['CYATY', 'Contemporary Amperex Technology Co., Limited/ADR'],
  ['COST', 'COSTCO WHOLESALE CORP /NEW'],
  ['BAC', 'BANK OF AMERICA CORP /DE/'],
  ['GE', 'GENERAL ELECTRIC CO'],
  ['KLAC', 'KLA CORP'],
  ['ARM', 'ARM HOLDINGS PLC /UK'],
  ['UNH', 'UNITEDHEALTH GROUP INC'],
  ['HD', 'HOME DEPOT, INC.'],
  ['KO', 'COCA COLA CO'],
  ['PG', 'PROCTER & GAMBLE Co'],
  ['CVX', 'CHEVRON CORP'],
  ['MS', 'MORGAN STANLEY'],
  ['HSBC', 'HSBC HOLDINGS PLC'],
  ['SNDK', 'Sandisk Corp'],
  ['MRK', 'Merck & Co., Inc.'],
  ['GEV', 'GE Vernova Inc.'],
  ['KXIAY', 'Kioxia Holdings Corporation/ADR'],
  ['HBCYF', 'HSBC HOLDINGS PLC'],
  ['NFLX', 'NETFLIX INC'],
  ['NVS', 'NOVARTIS AG'],
  ['GS', 'GOLDMAN SACHS GROUP INC'],
  ['RCIT', 'REELCAUSE INC'],
  ['AZN', 'ASTRAZENECA PLC'],
  ['NVSEF', 'NOVARTIS AG'],
  ['RY', 'ROYAL BANK OF CANADA'],
  ['PM', 'Philip Morris International Inc.'],
  ['PLTR', 'Palantir Technologies Inc.'],
  ['DELL', 'Dell Technologies Inc.'],
  ['PANW', 'Palo Alto Networks Inc'],
  ['PCCYF', 'PETROCHINA CO LTD'],
  ['TXN', 'TEXAS INSTRUMENTS INC'],
  ['MRVL', 'Marvell Technology, Inc.'],
  ['IBM', 'INTERNATIONAL BUSINESS MACHINES CORP'],
  ['RTX', 'RTX Corp'],
  ['WFC', 'WELLS FARGO & COMPANY/MN'],
  ['MBFJF', 'MITSUBISHI UFJ FINANCIAL GROUP INC'],
  ['BABAF', 'Alibaba Group Holding Ltd'],
  ['LIN', 'LINDE PLC'],
  ['C', 'CITIGROUP INC'],
  ['BABA', 'Alibaba Group Holding Ltd'],
  ['AXP', 'AMERICAN EXPRESS CO'],
  ['MUFG', 'MITSUBISHI UFJ FINANCIAL GROUP INC'],
  ['RYDAF', 'Shell plc'],
  ['WDC', 'WESTERN DIGITAL CORP'],
  ['GLW', 'CORNING INC /NY'],
  ['APH', 'AMPHENOL CORP /DE/'],
  ['ANET', 'Arista Networks, Inc.'],
  ['SHEL', 'Shell plc'],
  ['NVO', 'NOVO NORDISK A S'],
  ['STX', 'Seagate Technology Holdings plc'],
  ['NONOF', 'NOVO NORDISK A S'],
  ['BHP', 'BHP Group Ltd'],
  ['BHPLF', 'BHP Group Ltd'],
  ['IDEXF', 'Industria de Diseno Textil Inditex SA / ADR'],
  ['TOYOF', 'TOYOTA MOTOR CORP/'],
  ['TD', 'TORONTO DOMINION BANK'],
  ['BCDRF', 'Banco Santander, S.A.'],
  ['TM', 'TOYOTA MOTOR CORP/'],
  ['RTNTF', 'RIO TINTO LTD'],
  ['ABLZF', 'ABB LTD'],
  ['ABBNY', 'ABB LTD'],
  ['SAN', 'Banco Santander, S.A.'],
  ['AMGN', 'AMGEN INC'],
  ['QCOM', 'QUALCOMM INC/DE'],
  ['CRWD', 'CrowdStrike Holdings, Inc.'],
  ['ADI', 'ANALOG DEVICES INC'],
  ['MCD', 'MCDONALDS CORP'],
  ['TMO', 'THERMO FISHER SCIENTIFIC INC.'],
  ['PEP', 'PEPSICO INC'],
  ['SAPGF', 'SAP SE'],
  ['NEE', 'NEXTERA ENERGY INC'],
  ['TMUS', 'T-Mobile US, Inc.'],
  ['SAP', 'SAP SE'],
  ['VZ', 'VERIZON COMMUNICATIONS INC'],
  ['APP', 'AppLovin Corp'],
  ['TTE', 'TotalEnergies SE'],
  ['EADSF', 'Airbus SE/ADR'],
  ['DE', 'DEERE & CO'],
  ['BA', 'BOEING CO'],
  ['TJX', 'TJX COMPANIES INC /DE/'],
  ['DIS', 'Walt Disney Co'],
  ['UBS', 'UBS Group AG'],
  ['UNP', 'UNION PACIFIC CORP'],
  ['SMERY', 'Siemens Energy AG/ADR'],
  ['BUDFF', 'Anheuser-Busch InBev SA/NV'],
  ['WBKCY', 'WESTPAC BANKING CORP'],
  ['SCHW', 'SCHWAB CHARLES CORP'],
  ['WELL', 'WELLTOWER INC.'],
  ['BUD', 'Anheuser-Busch InBev SA/NV'],
  ['ABT', 'ABBOTT LABORATORIES'],
  ['ETN', 'Eaton Corp plc'],
  ['GILD', 'GILEAD SCIENCES, INC.'],
  ['BLK', 'BlackRock, Inc.'],
  ['SMEGF', 'Siemens Energy AG/ADR'],
  ['RIO', 'RIO TINTO PLC'],
  ['SMFNF', 'SUMITOMO MITSUI FINANCIAL GROUP, INC.'],
  ['RTPPF', 'RIO TINTO PLC'],
  ['ATEYY', 'ADVANTEST CORP'],
  ['SMFG', 'SUMITOMO MITSUI FINANCIAL GROUP, INC.'],
  ['IBKR', 'Interactive Brokers Group, Inc.'],
  ['ADTTF', 'ADVANTEST CORP'],
  ['SHOP', 'SHOPIFY INC.'],
  ['UBER', 'Uber Technologies, Inc'],
  ['T', 'AT&T INC.'],
  ['SCCO', 'SOUTHERN COPPER CORP/'],
  ['BX', 'Blackstone Inc.'],
  ['ISRG', 'INTUITIVE SURGICAL INC'],
  ['BTAFF', 'British American Tobacco p.l.c.'],
  ['BBVXF', 'BANCO BILBAO VIZCAYA ARGENTARIA, S.A.'],
  ['BBVA', 'BANCO BILBAO VIZCAYA ARGENTARIA, S.A.'],
  ['DTEGY', 'DEUTSCHE TELEKOM AG'],
  ['DTEGF', 'DEUTSCHE TELEKOM AG'],
  ['BKNG', 'Booking Holdings Inc.'],
  ['PFE', 'PFIZER INC'],
  ['DHR', 'DANAHER CORP /DE/'],
  ['BTI', 'British American Tobacco p.l.c.'],
  ['HDB', 'HDFC BANK LTD'],
  ['CB', 'Chubb Ltd'],
  ['CVS', 'CVS HEALTH Corp'],
  ['UL', 'UNILEVER PLC'],
  ['VRT', 'Vertiv Holdings Co'],
  ['CRM', 'Salesforce, Inc.'],
  ['MRAAF', 'Murata Manufacturing Co., Ltd./ADR'],
  ['UNLYF', 'UNILEVER PLC'],
  ['PGR', 'PROGRESSIVE CORP/OH/'],
  ['PLD', 'Prologis, Inc.'],
  ['SNEJF', 'Sony Group Corp'],
  ['COP', 'CONOCOPHILLIPS'],
  ['AIQUF', 'L AIR LIQUIDE SA /FI'],
  ['VRTX', 'VERTEX PHARMACEUTICALS INC / MA'],
  ['HTHIF', 'HITACHI LTD'],
  ['HTHIY', 'HITACHI LTD'],
  ['LOW', 'LOWES COMPANIES INC'],
  ['COF', 'CAPITAL ONE FINANCIAL CORP'],
  ['BMO', 'BANK OF MONTREAL /CAN/'],
  ['PH', 'Parker-Hannifin Corp'],
  ['ENB', 'ENBRIDGE INC'],
  ['IFNNY', 'INFINEON TECHNOLOGIES AG'],
  ['MO', 'ALTRIA GROUP, INC.'],
  ['SYK', 'STRYKER CORP'],
  ['SPGI', 'S&P Global Inc.'],
  ['NEMCL', 'NEWMONT Corp /DE/'],
  ['SONY', 'Sony Group Corp'],
  ['BMY', 'BRISTOL MYERS SQUIBB CO'],
  ['SBUX', 'STARBUCKS CORP'],
  ['LMT', 'LOCKHEED MARTIN CORP'],
  ['IFNNF', 'INFINEON TECHNOLOGIES AG'],
  ['MFG', 'MIZUHO FINANCIAL GROUP INC'],
  ['WFC-PC', 'WELLS FARGO & COMPANY/MN'],
  ['MZHOF', 'MIZUHO FINANCIAL GROUP INC'],
  ['FTNT', 'Fortinet, Inc.'],
  ['HWM', 'Howmet Aerospace Inc.'],
  ['SO', 'SOUTHERN CO'],
  ['TT', 'Trane Technologies plc'],
  ['PDD', 'PDD Holdings Inc.'],
  ['PWR', 'QUANTA SERVICES, INC.'],
  ['EQIX', 'EQUINIX INC'],
  ['BNS', 'BANK OF NOVA SCOTIA'],
  ['GSK', 'GSK plc'],
  ['CM', 'CANADIAN IMPERIAL BANK OF COMMERCE /CAN/'],
  ['PBR', 'PETROBRAS - PETROLEO BRASILEIRO SA'],
  ['IBN', 'ICICI BANK LTD'],
  ['CDNS', 'CADENCE DESIGN SYSTEMS INC'],
  ['SNHIY', 'Sany Heavy Industries Co., Ltd./ADR'],
  ['SNY', 'Sanofi'],
  ['GLAXF', 'GSK plc'],
  ['SNYNF', 'Sanofi'],
  ['CILJF', 'CHINA LIFE INSURANCE CO LTD'],
]

const pickUniverse = (items, symbols) => {
  const wanted = new Set(symbols)
  return items.filter(([symbol]) => wanted.has(symbol))
}

export const STOCK_UNIVERSES = {
  us100b: {
    label: 'US $100B+ Top 200',
    items: US_100B_TOP_200,
  },
  us100bQuality: {
    label: 'US Quality 100B+',
    items: pickUniverse(US_100B_TOP_200, [
      'NVDA', 'GOOGL', 'GOOG', 'AAPL', 'MSFT', 'AMZN', 'TSM', 'AVGO', 'META', 'MU',
      'LLY', 'WMT', 'ASML', 'V', 'JNJ', 'AMAT', 'LRCX', 'CAT', 'CSCO', 'MA',
      'TSMWF', 'ORCL', 'COST', 'GE', 'KLAC', 'HD', 'KO', 'PG', 'SNDK', 'MRK',
      'GEV', 'NFLX', 'NVS', 'AZN', 'PLTR', 'TXN', 'MRVL', 'IBM', 'LIN', 'AXP',
      'WDC', 'GLW', 'APH', 'ANET', 'NVO', 'STX', 'ABLZF', 'ABBNY', 'AMGN', 'PEP',
      'TMUS', 'SAP', 'VZ', 'APP', 'DE', 'TJX', 'UNP', 'SMERY', 'SCHW', 'ETN',
      'GILD', 'SMEGF', 'IBKR', 'ADTTF', 'UBER', 'T', 'SCCO', 'BX', 'ISRG', 'BBVA',
      'CB', 'VRT', 'CRM', 'PGR', 'VRTX', 'PH', 'SYK', 'BMY', 'LMT', 'FTNT',
      'HWM', 'TT', 'PDD', 'GSK', 'PBR', 'CDNS',
    ]),
  },
  us100bGrowth: {
    label: 'US Growth 100B+',
    items: pickUniverse(US_100B_TOP_200, [
      'NVDA', 'GOOGL', 'GOOG', 'AAPL', 'AMZN', 'AVGO', 'TSLA', 'META', 'MU', 'LLY',
      'AMD', 'INTC', 'V', 'CAT', 'MA', 'ORCL', 'CYATY', 'GE', 'ARM', 'PG',
      'CVX', 'SNDK', 'MRK', 'GEV', 'AZN', 'PM', 'PLTR', 'TXN', 'MBFJF', 'MUFG',
      'WDC', 'GLW', 'APH', 'STX', 'ABLZF', 'ABBNY', 'QCOM', 'CRWD', 'ADI', 'PEP',
      'NEE', 'APP', 'EADSF', 'SMERY', 'GILD', 'SMEGF', 'SMFNF', 'SMFG', 'SHOP', 'UBER',
      'SCCO', 'BBVXF', 'BBVA', 'BKNG', 'PFE', 'CB', 'SNEJF', 'COP', 'COF', 'IFNNY',
      'SONY', 'IFNNF', 'MFG', 'MZHOF', 'FTNT', 'SO', 'PWR', 'GSK', 'PBR', 'IBN',
      'SNY', 'GLAXF', 'SNYNF', 'CILJF',
    ]),
  },
  us100bValue: {
    label: 'US Value 100B+',
    items: pickUniverse(US_100B_TOP_200, [
      'AMZN', 'TSM', 'BRK-A', 'BRK-B', 'WMT', 'XOM', 'TSMWF', 'COST', 'BAC', 'UNH',
      'HD', 'PG', 'CVX', 'MRK', 'AZN', 'DELL', 'IBM', 'RTX', 'WFC', 'BABAF',
      'BABA', 'AXP', 'SHEL', 'NVO', 'TM', 'TMO', 'PEP', 'TMUS', 'SAP', 'VZ',
      'TTE', 'DE', 'TJX', 'DIS', 'SMERY', 'ABT', 'SMEGF', 'ADTTF', 'UBER', 'T',
      'BBVA', 'DTEGY', 'DTEGF', 'BKNG', 'PFE', 'CB', 'CRM', 'PGR', 'SNEJF', 'COP',
      'HTHIF', 'HTHIY', 'LOW', 'COF', 'ENB', 'SYK', 'SONY', 'BMY', 'SBUX', 'LMT',
      'SO', 'PDD', 'PWR', 'GSK', 'PBR', 'SNY',
    ]),
  },
  mega: {
    label: 'Mega Cap',
    items: [
      ['AAPL', 'Apple'],
      ['MSFT', 'Microsoft'],
      ['NVDA', 'NVIDIA'],
      ['AMZN', 'Amazon'],
      ['META', 'Meta Platforms'],
      ['GOOGL', 'Alphabet Class A'],
      ['GOOG', 'Alphabet Class C'],
      ['TSLA', 'Tesla'],
      ['AVGO', 'Broadcom'],
      ['BRK-B', 'Berkshire Hathaway'],
      ['LLY', 'Eli Lilly'],
      ['JPM', 'JPMorgan Chase'],
      ['V', 'Visa'],
      ['MA', 'Mastercard'],
      ['UNH', 'UnitedHealth'],
      ['COST', 'Costco'],
      ['WMT', 'Walmart'],
      ['NFLX', 'Netflix'],
      ['ORCL', 'Oracle'],
      ['AMD', 'Advanced Micro Devices'],
    ],
  },
  aiSemi: {
    label: 'AI / Semi',
    items: [
      ['NVDA', 'NVIDIA'],
      ['AMD', 'Advanced Micro Devices'],
      ['AVGO', 'Broadcom'],
      ['TSM', 'Taiwan Semiconductor'],
      ['ASML', 'ASML Holding'],
      ['ARM', 'Arm Holdings'],
      ['MU', 'Micron Technology'],
      ['MRVL', 'Marvell Technology'],
      ['SMCI', 'Super Micro Computer'],
      ['INTC', 'Intel'],
      ['QCOM', 'Qualcomm'],
      ['AMAT', 'Applied Materials'],
      ['LRCX', 'Lam Research'],
      ['KLAC', 'KLA'],
      ['TER', 'Teradyne'],
      ['DELL', 'Dell Technologies'],
      ['HPE', 'Hewlett Packard Enterprise'],
      ['ANET', 'Arista Networks'],
      ['PLTR', 'Palantir'],
      ['SNOW', 'Snowflake'],
    ],
  },
  highBeta: {
    label: 'High Beta',
    items: [
      ['TSLA', 'Tesla'],
      ['PLTR', 'Palantir'],
      ['COIN', 'Coinbase'],
      ['HOOD', 'Robinhood'],
      ['MSTR', 'MicroStrategy'],
      ['CRCL', 'Circle Internet Group'],
      ['RBLX', 'Roblox'],
      ['SOFI', 'SoFi Technologies'],
      ['RIVN', 'Rivian'],
      ['LCID', 'Lucid Group'],
      ['MARA', 'MARA Holdings'],
      ['RIOT', 'Riot Platforms'],
      ['IREN', 'IREN'],
      ['WULF', 'TeraWulf'],
      ['UPST', 'Upstart'],
      ['DKNG', 'DraftKings'],
      ['AFRM', 'Affirm'],
      ['SHOP', 'Shopify'],
      ['ROKU', 'Roku'],
      ['NET', 'Cloudflare'],
    ],
  },
  etf: {
    label: 'ETF Core',
    items: [
      ['SPY', 'SPDR S&P 500 ETF'],
      ['QQQ', 'Invesco QQQ'],
      ['IWM', 'iShares Russell 2000 ETF'],
      ['DIA', 'SPDR Dow Jones Industrial Average ETF'],
      ['VOO', 'Vanguard S&P 500 ETF'],
      ['VTI', 'Vanguard Total Stock Market ETF'],
      ['SMH', 'VanEck Semiconductor ETF'],
      ['XLK', 'Technology Select Sector SPDR'],
      ['XLF', 'Financial Select Sector SPDR'],
      ['XLE', 'Energy Select Sector SPDR'],
      ['XLI', 'Industrial Select Sector SPDR'],
      ['XLV', 'Health Care Select Sector SPDR'],
      ['XLY', 'Consumer Discretionary Select Sector SPDR'],
      ['XLP', 'Consumer Staples Select Sector SPDR'],
      ['TLT', 'iShares 20+ Year Treasury Bond ETF'],
      ['GLD', 'SPDR Gold Shares'],
      ['SLV', 'iShares Silver Trust'],
      ['USO', 'United States Oil Fund'],
      ['TQQQ', 'ProShares UltraPro QQQ'],
      ['SQQQ', 'ProShares UltraPro Short QQQ'],
    ],
  },
}

export const CORE_CRYPTO_SYMBOLS = new Set([
  'BTC',
  'ETH',
  'SOL',
  'BNB',
  'XRP',
  'DOGE',
  'ADA',
  'LINK',
  'AVAX',
  'TON',
  'TRX',
  'LTC',
  'BCH',
  'DOT',
  'NEAR',
])

export function stockUniverseEntries(keys = Object.keys(STOCK_UNIVERSES)) {
  const seen = new Set()
  const out = []
  for (const key of keys) {
    for (const [symbol, name] of STOCK_UNIVERSES[key]?.items ?? []) {
      if (seen.has(symbol)) continue
      seen.add(symbol)
      out.push({ symbol, apiSymbol: symbol, type: 'stock', source: 'yahoo', name })
    }
  }
  return out
}
